name: leather_ecommerce_app
description: A modern minimalist ecommerce app inspired by Leatherology
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  
  # Image handling
  cached_network_image: ^3.3.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Google Sheets API
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  
  # Authentication (temporary local storage solution)
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
